# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Categories:

# Customize option
customize:
    logo:
        width: 140
        height: 40
        url: /images/common/logo-header.png
    theme_color: '#59abdb'
    highlight: androidstudio
    sidebar: left # sidebar position, options: left, right
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: /images/common/favicon.ico # path to favicon
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        mail: mailto:merryyear45@gmail.com
        linkedin: https://www.linkedin.com/in/merryyear45
        gitlab: https://gitlab.com/intiwatana
        github: https://github.com/intiwatana
        rss: /feed.xml

# Widgets
widgets:
    - catalog
    - recent_posts
    - category
    - archive
    - tagcloud

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: intiwatana-github-io # enter disqus shortname here
    facebook: # enter true to enable



# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: UA-117835173-1 # enter the tracking ID for your Google Analytics
    naver_site_verification: b16b04b7844cbfe72dc8a0aae45d23ef9fc5c4b6
    baidu_analytics: # enter Baidu Analytics hash key
    bing_site_verification: # enter Bing verification key here
    mathjax: false # options: true, false
    hexo-reference: true #footnote option added

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
